"""empty message

Revision ID: 0ab95115dfa8
Revises: b5177997a452
Create Date: 2023-05-27 23:42:57.234697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ab95115dfa8'
down_revision = 'b5177997a452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('healthcareworker', sa.Column('role', sa.String(), nullable=True))
    op.drop_column('healthcareworker', 'medical_speciality')
    op.drop_column('healthcareworker', 'worker_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('healthcareworker', sa.Column('worker_type', sa.VARCHAR(), nullable=False))
    op.add_column('healthcareworker', sa.Column('medical_speciality', sa.VARCHAR(), nullable=True))
    op.drop_column('healthcareworker', 'role')
    # ### end Alembic commands ###
