"""Initial migration

Revision ID: 147be0bc2996
Revises: 
Create Date: 2023-04-25 10:20:37.702328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147be0bc2996'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('department_name', sa.String(), nullable=False),
    sa.Column('department_email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('department_id'),
    sa.UniqueConstraint('department_email'),
    sa.UniqueConstraint('department_id'),
    sa.UniqueConstraint('department_name')
    )
    op.create_table('patient',
    sa.Column('id_patient', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('phone_number', sa.BigInteger(), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('CF', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id_patient'),
    sa.UniqueConstraint('id_patient')
    )
    op.create_table('healthcareworker',
    sa.Column('id_worker', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('worker_type', sa.String(), nullable=False),
    sa.Column('medical_speciality', sa.String(), nullable=True),
    sa.Column('nurse_grade', sa.String(), nullable=True),
    sa.Column('dep_rif', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dep_rif'], ['department.department_id'], ),
    sa.PrimaryKeyConstraint('id_worker'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_worker')
    )
    op.create_table('hospedalization',
    sa.Column('hospedalization_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('hosp_reason', sa.Text(), nullable=False),
    sa.Column('pat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pat_id'], ['patient.id_patient'], ),
    sa.PrimaryKeyConstraint('hospedalization_id'),
    sa.UniqueConstraint('hospedalization_id')
    )
    op.create_table('medicalrecord',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('terapy', sa.Text(), nullable=True),
    sa.Column('dep_id', sa.Integer(), nullable=False),
    sa.Column('pat_id', sa.Integer(), nullable=False),
    sa.Column('hosp_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dep_id'], ['department.department_id'], ),
    sa.ForeignKeyConstraint(['hosp_id'], ['hospedalization.hospedalization_id'], ),
    sa.ForeignKeyConstraint(['pat_id'], ['patient.id_patient'], ),
    sa.PrimaryKeyConstraint('record_id'),
    sa.UniqueConstraint('record_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medicalrecord')
    op.drop_table('hospedalization')
    op.drop_table('healthcareworker')
    op.drop_table('patient')
    op.drop_table('department')
    # ### end Alembic commands ###
