"""add_admin

Revision ID: 27894067e221
Revises: 843d6f6fd85a
Create Date: 2023-05-08 15:06:16.759163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27894067e221'
down_revision = '843d6f6fd85a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id_admin', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_admin'),
    sa.UniqueConstraint('id_admin')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###
