"""add column to dicom_image table

Revision ID: 6503de31b8e9
Revises: 108a1df47f7b
Create Date: 2023-06-10 17:08:23.244879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6503de31b8e9'
down_revision = '108a1df47f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dicom', sa.Column('notified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dicom', 'notified')
    # ### end Alembic commands ###
