"""empty message

Revision ID: 709cb0c7f1e0
Revises: b41ceab74a73
Create Date: 2023-04-24 15:53:05.661218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709cb0c7f1e0'
down_revision = 'b41ceab74a73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bioimage')
    op.drop_table('healthcareworker')
    op.drop_table('biosignal')
    op.drop_table('patient')
    op.drop_table('hospedalization')
    op.drop_table('medicalrecord')
    op.drop_table('department')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('department_id', sa.INTEGER(), nullable=False),
    sa.Column('department_name', sa.VARCHAR(), nullable=False),
    sa.Column('department_email', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('department_id'),
    sa.UniqueConstraint('department_email'),
    sa.UniqueConstraint('department_id'),
    sa.UniqueConstraint('department_name')
    )
    op.create_table('medicalrecord',
    sa.Column('record_id', sa.INTEGER(), nullable=False),
    sa.Column('terapy', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('record_id'),
    sa.UniqueConstraint('record_id')
    )
    op.create_table('hospedalization',
    sa.Column('hospedalization_id', sa.INTEGER(), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('hosp_reason', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('hospedalization_id'),
    sa.UniqueConstraint('hospedalization_id')
    )
    op.create_table('patient',
    sa.Column('id_patient', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('surname', sa.VARCHAR(), nullable=False),
    sa.Column('birth_date', sa.DATE(), nullable=False),
    sa.Column('phone_number', sa.BIGINT(), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=False),
    sa.Column('city', sa.VARCHAR(), nullable=False),
    sa.Column('CF', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id_patient'),
    sa.UniqueConstraint('id_patient')
    )
    op.create_table('biosignal',
    sa.Column('id_Biosignal', sa.INTEGER(), nullable=False),
    sa.Column('test_name', sa.VARCHAR(), nullable=False),
    sa.Column('exame_type', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id_Biosignal'),
    sa.UniqueConstraint('id_Biosignal')
    )
    op.create_table('healthcareworker',
    sa.Column('id_worker', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('surname', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('worker_type', sa.VARCHAR(), nullable=False),
    sa.Column('medical_speciality', sa.VARCHAR(), nullable=True),
    sa.Column('nurse_grade', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id_worker'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_worker')
    )
    op.create_table('bioimage',
    sa.Column('id_bioimage', sa.INTEGER(), nullable=False),
    sa.Column('exame_type', sa.VARCHAR(), nullable=False),
    sa.Column('exame_name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id_bioimage'),
    sa.UniqueConstraint('id_bioimage')
    )
    # ### end Alembic commands ###
