"""add relationship to dicom_image table

Revision ID: 884783264ea5
Revises: 6503de31b8e9
Create Date: 2023-06-10 17:22:01.697551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884783264ea5'
down_revision = '6503de31b8e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dicom', sa.Column('healthcareworker_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dicom', 'healthcareworker', ['healthcareworker_id'], ['id_worker'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dicom', type_='foreignkey')
    op.drop_column('dicom', 'healthcareworker_id')
    # ### end Alembic commands ###
