"""empty message

Revision ID: 9c87686e1472
Revises: f41107613457
Create Date: 2023-06-04 12:52:59.880003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c87686e1472'
down_revision = 'f41107613457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('registered', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'registered')
    # ### end Alembic commands ###
