"""empty message

Revision ID: b41ceab74a73
Revises: 
Create Date: 2023-04-23 20:17:54.810329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b41ceab74a73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bioimage',
    sa.Column('id_bioimage', sa.Integer(), nullable=False),
    sa.Column('exame_type', sa.String(), nullable=False),
    sa.Column('exame_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_bioimage'),
    sa.UniqueConstraint('id_bioimage')
    )
    op.create_table('biosignal',
    sa.Column('id_Biosignal', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(), nullable=False),
    sa.Column('exame_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_Biosignal'),
    sa.UniqueConstraint('id_Biosignal')
    )
    op.create_table('department',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('department_name', sa.String(), nullable=False),
    sa.Column('department_email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('department_id'),
    sa.UniqueConstraint('department_email'),
    sa.UniqueConstraint('department_id'),
    sa.UniqueConstraint('department_name')
    )
    op.create_table('healthcareworker',
    sa.Column('id_worker', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('worker_type', sa.String(), nullable=False),
    sa.Column('medical_speciality', sa.String(), nullable=True),
    sa.Column('nurse_grade', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_worker'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_worker')
    )
    op.create_table('hospedalization',
    sa.Column('hospedalization_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('hosp_reason', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('hospedalization_id'),
    sa.UniqueConstraint('hospedalization_id')
    )
    op.create_table('medicalrecord',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('terapy', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('record_id'),
    sa.UniqueConstraint('record_id')
    )
    op.create_table('patient',
    sa.Column('id_patient', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('phone_number', sa.BigInteger(), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('CF', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id_patient'),
    sa.UniqueConstraint('id_patient')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient')
    op.drop_table('medicalrecord')
    op.drop_table('hospedalization')
    op.drop_table('healthcareworker')
    op.drop_table('department')
    op.drop_table('biosignal')
    op.drop_table('bioimage')
    # ### end Alembic commands ###
