"""complete db

Revision ID: c4724f78ba7b
Revises: 147be0bc2996
Create Date: 2023-04-25 10:32:06.418327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4724f78ba7b'
down_revision = '147be0bc2996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dicom',
    sa.Column('dicom_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=120), nullable=True),
    sa.Column('exame_type', sa.String(), nullable=False),
    sa.Column('exame_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('dicom_id'),
    sa.UniqueConstraint('dicom_id')
    )
    op.create_table('dicom_data_element',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('dicom_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dicom_id'], ['dicom.dicom_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_dicom',
    sa.Column('id_dicom', sa.Integer(), nullable=False),
    sa.Column('medical_record_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_dicom'], ['dicom.dicom_id'], ),
    sa.ForeignKeyConstraint(['medical_record_id'], ['medicalrecord.record_id'], ),
    sa.PrimaryKeyConstraint('id_dicom')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_dicom')
    op.drop_table('dicom_data_element')
    op.drop_table('dicom')
    # ### end Alembic commands ###
