"""empty message

Revision ID: caa718b0e6cb
Revises: c96f0a5893dd
Create Date: 2023-05-22 11:26:45.430969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caa718b0e6cb'
down_revision = 'c96f0a5893dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_group',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor'], ['healthcareworker.id_worker'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id_patient'], ),
    sa.PrimaryKeyConstraint('patient_id', 'doctor')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_group')
    # ### end Alembic commands ###
