"""inital_migration

Revision ID: cd0f2ecdba83
Revises: 
Create Date: 2023-06-10 19:36:03.759749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd0f2ecdba83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id_admin', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_admin'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_admin')
    )
    op.create_table('department',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('department_name', sa.String(), nullable=False),
    sa.Column('department_email', sa.String(), nullable=False),
    sa.Column('head_of_department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['head_of_department_id'], ['healthcareworker.id_worker'], ),
    sa.PrimaryKeyConstraint('department_id'),
    sa.UniqueConstraint('department_email'),
    sa.UniqueConstraint('department_id'),
    sa.UniqueConstraint('department_name')
    )
    op.create_table('healthcareworker',
    sa.Column('id_worker', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('CF', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('birth_date', sa.String(), nullable=True),
    sa.Column('hw_role_not_doctor', sa.String(), nullable=True),
    sa.Column('nurse_grade', sa.String(), nullable=True),
    sa.Column('special_code', sa.Integer(), nullable=True),
    sa.Column('dep_rif', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dep_rif'], ['department.department_id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], ),
    sa.PrimaryKeyConstraint('id_worker'),
    sa.UniqueConstraint('CF'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_worker')
    )
    op.create_table('patient',
    sa.Column('id_patient', sa.Integer(), nullable=False),
    sa.Column('password_patient', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('phone_number', sa.BigInteger(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('CF', sa.Text(), nullable=True),
    sa.Column('registered', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_patient'),
    sa.UniqueConstraint('CF'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_patient'),
    sa.UniqueConstraint('password_patient')
    )
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['healthcareworker.id_worker'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id_patient'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dicom',
    sa.Column('dicom_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=120), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('exame_name', sa.String(), nullable=True),
    sa.Column('image_dimension', sa.Integer(), nullable=False),
    sa.Column('base64_data', sa.Text(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.Column('healthcareworker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['healthcareworker_id'], ['healthcareworker.id_worker'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id_patient'], ),
    sa.PrimaryKeyConstraint('dicom_id'),
    sa.UniqueConstraint('dicom_id')
    )
    op.create_table('hospedalization',
    sa.Column('hospedalization_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('hosp_reason', sa.Text(), nullable=False),
    sa.Column('pat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pat_id'], ['patient.id_patient'], ),
    sa.PrimaryKeyConstraint('hospedalization_id'),
    sa.UniqueConstraint('hospedalization_id')
    )
    op.create_table('patient_group',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor'], ['healthcareworker.id_worker'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id_patient'], ),
    sa.PrimaryKeyConstraint('patient_id', 'doctor')
    )
    op.create_table('medicalrecord',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('terapy', sa.Text(), nullable=True),
    sa.Column('dep_id', sa.Integer(), nullable=True),
    sa.Column('pat_id', sa.Integer(), nullable=True),
    sa.Column('hosp_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dep_id'], ['department.department_id'], ),
    sa.ForeignKeyConstraint(['hosp_id'], ['hospedalization.hospedalization_id'], ),
    sa.ForeignKeyConstraint(['pat_id'], ['patient.id_patient'], ),
    sa.PrimaryKeyConstraint('record_id'),
    sa.UniqueConstraint('record_id')
    )
    op.create_table('medical_dicom',
    sa.Column('id_dicom', sa.Integer(), nullable=True),
    sa.Column('medical_record_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_dicom'], ['dicom.dicom_id'], ),
    sa.ForeignKeyConstraint(['medical_record_id'], ['medicalrecord.record_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_dicom')
    op.drop_table('medicalrecord')
    op.drop_table('patient_group')
    op.drop_table('hospedalization')
    op.drop_table('dicom')
    op.drop_table('appointment')
    op.drop_table('patient')
    op.drop_table('healthcareworker')
    op.drop_table('department')
    op.drop_table('admin')
    # ### end Alembic commands ###
